s2bitdepth = {
    "Traffic"            :8,
    "PeopleOnStreet"     :8,
    "Nebuta"             :10,
    "SteamLocomotive"    :10,
    "Kimono1"            :8,
    "ParkScene"          :8,
    "Cactus"             :8,
    "BQTerrace"          :8,
    "BasketballDrive"    :8,
    "RaceHorses"         :8,
    "BQMall"             :8,
    "PartyScene"         :8,
    "BasketballDrill"    :8,
    "RaceHorsesLow"      :8,
    "BQSquare"           :8,
    "BlowingBubbles"     :8,
    "BasketballPass"     :8,
    "FourPeople"         :8,
    "Johnny"             :8,
    "KristenAndSara"     :8,
    "BasketballDrillText":8,
    "ChinaSpeed"         :8,
    "SlideEditing"       :8,
    "SlideShow"          :8,
    }