s2class = {
    "Traffic"            :"A",
    "PeopleOnStreet"     :"A",
    "Nebuta"             :"A",
    "SteamLocomotive"    :"A",
    "Kimono1"            :"B",
    "ParkScene"          :"B",
    "Cactus"             :"B",
    "BQTerrace"          :"B",
    "BasketballDrive"    :"B",
    "RaceHorses"         :"C",
    "BQMall"             :"C",
    "PartyScene"         :"C",
    "BasketballDrill"    :"C",
    "RaceHorsesLow"      :"D",
    "BQSquare"           :"D",
    "BlowingBubbles"     :"D",
    "BasketballPass"     :"D",
    "FourPeople"         :"E",
    "Johnny"             :"E",
    "KristenAndSara"     :"E",
    "BasketballDrillText":"F",
    "ChinaSpeed"         :"F",
    "SlideEditing"       :"F",
    "SlideShow"          :"F",
    }