s2frames = {
    "Traffic"            :150,
    "PeopleOnStreet"     :150,
    "Nebuta"             :300,
    "SteamLocomotive"    :300,
    "Kimono1"            :240,
    "ParkScene"          :240,
    "Cactus"             :500,
    "BQTerrace"          :600,
    "BasketballDrive"    :500,
    "RaceHorses"         :300,
    "BQMall"             :600,
    "PartyScene"         :500,
    "BasketballDrill"    :500,
    "RaceHorsesLow"      :300,
    "BQSquare"           :600,
    "BlowingBubbles"     :500,
    "BasketballPass"     :500,
    "FourPeople"         :600,
    "Johnny"             :600,
    "KristenAndSara"     :600,
    "BasketballDrillText":500,
    "ChinaSpeed"         :500,
    "SlideEditing"       :300,
    "SlideShow"          :500,
    }