s2framerate = {
    "Traffic"            :30,
    "PeopleOnStreet"     :30,
    "Nebuta"             :60,
    "SteamLocomotive"    :60,
    "Kimono1"            :24,
    "ParkScene"          :24,
    "Cactus"             :50,
    "BQTerrace"          :60,
    "BasketballDrive"    :50,
    "RaceHorses"         :30,
    "BQMall"             :60,
    "PartyScene"         :50,
    "BasketballDrill"    :50,
    "RaceHorsesLow"      :30,
    "BQSquare"           :60,
    "BlowingBubbles"     :50,
    "BasketballPass"     :50,
    "FourPeople"         :60,
    "Johnny"             :60,
    "KristenAndSara"     :60,
    "BasketballDrillText":50,
    "ChinaSpeed"         :30,
    "SlideEditing"       :30,
    "SlideShow"          :20,
    }