s2name = {
    "Traffic"            :"Traffic",
    "PeopleOnStreet"     :"PeopleOnStreet",
    "Nebuta"             :"NebutaFestival",
    "SteamLocomotive"    :"SteamLocomotiveTrain", 
    "Kimono1"            :"Kimono1",
    "ParkScene"          :"ParkScene",
    "Cactus"             :"Cactus",
    "BQTerrace"          :"BQTerrace",
    "BasketballDrive"    :"BasketballDrive",
    "RaceHorses"         :"RaceHorses",
    "BQMall"             :"BQMall",
    "PartyScene"         :"PartyScene",            
    "BasketballDrill"    :"BasketballDrill",
    "RaceHorsesLow"      :"RaceHorsesLow",
    "BQSquare"           :"BQSquare",
    "BlowingBubbles"     :"BlowingBubbles",
    "BasketballPass"     :"BasketballPass",
    "FourPeople"         :"FourPeople",
    "Johnny"             :"Johnny",
    "KristenAndSara"     :"KristenAndSara",
    "BasketballDrillText":"BasketballDrillText",
    "ChinaSpeed"         :"ChinaSpeed",
    "SlideEditing"       :"SlideEditing",
    "SlideShow"          :"SlideShow",
    }